# -*- coding: utf-8 -*-
"""maisprototype.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y3OKdhGu8eNdHfUIggEEIsn-0h7IqXvf
"""

import pandas as pd
import requests

# 1. 定義參數 (以 Poitou-Charentes 為例)
LAT, LON = 46.58, 0.34  # Poitiers 座標
START_DATE = "19950101"
END_DATE = "20251231" # 視當前最新數據而定

def fetch_nasa_data(lat, lon, start, end):
    url = f"https://power.larc.nasa.gov/api/temporal/daily/point?parameters=T2M_MAX,T2M_MIN,PRECTOTCORR&community=AG&longitude={lon}&latitude={lat}&start={start}&end={end}&format=JSON"
    response = requests.get(url)
    data = response.json()

    # 轉化為 DataFrame
    df = pd.DataFrame(data['properties']['parameter'])
    df.index = pd.to_datetime(df.index)
    df.columns = ['Tmax', 'Tmin', 'Rain']
    return df

# 執行抓取
weather_df = fetch_nasa_data(LAT, LON, START_DATE, END_DATE)
print(weather_df.head())

import numpy as np

def calculate_gdd(df, base=6, cap=30):
    # 限制氣溫邊界以符合玉米生理特性
    t_max_capped = df['Tmax'].clip(upper=cap)
    t_min_capped = df['Tmin'].clip(lower=base)
    # 計算每日積溫
    gdd = ((t_max_capped + t_min_capped) / 2) - base
    return gdd.clip(lower=0)

# 1. 計算每日積溫並加入表格
weather_df['GDD'] = calculate_gdd(weather_df)

# 2. 定義品種閾值 (ARVALIS 參考值)
varieties = {
    'Precoce': {'flowering': 900, 'maturity': 1500},
    'Demi-tardif': {'flowering': 950, 'maturity': 1700},
    'Tardif': {'flowering': 1050, 'maturity': 1900}
}

print("積溫計算完成，準備模擬每年生長週期...")

import pandas as pd

def run_growth_simulation(weather_df, varieties):
    results = []

    # 按年份進行循環處理
    for year in range(weather_df.index.year.min(), weather_df.index.year.max() + 1):
        year_data = weather_df[weather_df.index.year == year].copy()

        # 假設每年 4 月 15 日播種 (Semis)
        planting_date = pd.Timestamp(year=year, month=4, day=15)
        growing_season = year_data[year_data.index >= planting_date]

        # 對 3 種品種分別計算
        for var_name, thresholds in varieties.items():
            cumulative_gdd = 0
            flowering_date = None

            # 1. 尋找開花日
            for date, day_row in growing_season.iterrows():
                cumulative_gdd += day_row['GDD']
                if cumulative_gdd >= thresholds['flowering'] and flowering_date is None:
                    flowering_date = date
                    break

            if flowering_date:
                # 2. 定義敏感窗口 (開花前後 10 天)
                window_start = flowering_date - pd.Timedelta(days=10)
                window_end = flowering_date + pd.Timedelta(days=10)
                window_data = year_data[(year_data.index >= window_start) & (year_data.index <= window_end)]

                # 3. 計算壓力指標
                heat_stress_days = (window_data['Tmax'] > 35).sum()
                total_rain = window_data['Rain'].sum()
                # 簡單假設夏季日蒸散量為 5mm 作為基準
                water_deficit = total_rain - (len(window_data) * 5)

                results.append({
                    'Year': year,
                    'Variety': var_name,
                    'Flowering_Date': flowering_date.strftime('%Y-%m-%d'),
                    'Heat_Stress_Days': heat_stress_days,
                    'Water_Deficit_mm': water_deficit
                })

    return pd.DataFrame(results)

# 執行模擬
varieties = {
    'Precoce': {'flowering': 900},
    'Demi-tardif': {'flowering': 950},
    'Tardif': {'flowering': 1050}
}

stress_report = run_growth_simulation(weather_df, varieties)

# 儲存最終結果
stress_report.to_csv("maize_stress_index_report.csv", index=False)
print("年度壓力指標報告已生成！")
print(stress_report.head(10))

import matplotlib.pyplot as plt
import seaborn as sns

def estimate_yield(df):
    # 設定基礎潛在產量
    potential_yield = 12.0

    # 計算熱損失：每 1 天熱壓天數減產 3.5%
    heat_loss = df['Heat_Stress_Days'] * 0.035

    # 計算水損失：每 10mm 虧缺減產 1% (僅計算負值部分)
    water_loss = (df['Water_Deficit_mm'].abs() / 10.0) * 0.01

    # 計算模擬產量
    sim_yield = potential_yield * (1 - heat_loss - water_loss)
    # 確保產量不低於 0
    return sim_yield.clip(lower=0)

# 1. 執行產量估算
stress_report['Sim_Yield'] = estimate_yield(stress_report)

# 2. 視覺化：風險密度分佈圖 (這就是 Phase 3.2 的 UI 原型)
plt.figure(figsize=(10, 6))
sns.kdeplot(data=stress_report, x='Sim_Yield', hue='Variety', fill=True, common_norm=False, palette='viridis')

plt.title('Yield Distribution & Risk Exposure (1995-2025)', fontsize=14)
plt.xlabel('Simulated Yield (t/ha)', fontsize=12)
plt.ylabel('Probability Density', fontsize=12)
plt.axvline(x=6, color='red', linestyle='--', label='Critical Loss Threshold') # 設 6 噸為破產線
plt.legend()
plt.grid(alpha=0.3)
plt.show()

# 儲存包含產量的完整報告
stress_report.to_csv("maize_yield_risk_report.csv", index=False)
print("產量風險模擬完成，報告已儲存至 maize_yield_risk_report.csv")

import numpy as np
from scipy.optimize import minimize

# 1. 準備數據：將數據轉為「年份 x 品種」的產量矩陣
pivot_yield = stress_report.pivot(index='Year', columns='Variety', values='Sim_Yield')

# 2. 定義 CVaR 計算函數 (計算最差 5% 年份的平均損失)
def calculate_cvar(weights, yield_matrix, alpha=0.05):
    # 計算該權重組合下的農場總產量序列
    portfolio_yield = np.dot(yield_matrix, weights)
    # 找出最差的 alpha 分位數 (例如最差的 5% 年份)
    var_threshold = np.percentile(portfolio_yield, alpha * 100)
    # 計算低於該閾值的平均產量 (即 CVaR)
    cvar = portfolio_yield[portfolio_yield <= var_threshold].mean()
    # 因為我們要「最小化風險」，所以取負值讓優化器去跑
    return -cvar

# 3. 設定約束條件：權重之和必須等於 1 (100% 土地)
constraints = ({'type': 'eq', 'fun': lambda w: np.sum(w) - 1})
bounds = [(0, 1) for _ in range(len(pivot_yield.columns))] # 比例不能為負
init_guess = [1/3, 1/3, 1/3] # 初始猜測：平分土地

# 4. 執行優化
opt_result = minimize(calculate_cvar, init_guess, args=(pivot_yield.values,),
                      bounds=bounds, constraints=constraints)

optimal_weights = dict(zip(pivot_yield.columns, opt_result.x))

print("--- 決策輸出模組 (Actionable Output) ---")
for var, weight in optimal_weights.items():
    print(f"品種 {var} 建議播種比例: {weight*100:.1f}%")

import matplotlib.pyplot as plt
import seaborn as sns

# 1. 定義「有性格」的品種模型 (回應評審關於脆弱性差異的建議)
def estimate_yield_final(df):
    configs = {
        'Precoce': {'pot': 10.5, 'heat_sens': 0.02},     # 早熟：潛力一般，但非常耐熱
        'Demi-tardif': {'pot': 12.0, 'heat_sens': 0.035}, # 中熟：平衡型
        'Tardif': {'pot': 14.5, 'heat_sens': 0.07}       # 晚熟：潛力極高(14.5)，但遇到熱浪掉得極慘
    }

    yields = []
    for _, row in df.iterrows():
        cfg = configs[row['Variety']]
        # 非線性損失：熱壓天數越多，懲罰越重
        heat_loss = row['Heat_Stress_Days'] * cfg['heat_sens']
        # 水分損失
        water_loss = (abs(row['Water_Deficit_mm']) / 10.0) * 0.01

        y = cfg['pot'] * (1 - heat_loss - water_loss)
        yields.append(max(0, y))
    return yields

# 2. 更新產量數據並重新優化
stress_report['Sim_Yield'] = estimate_yield_final(stress_report)
pivot_yield = stress_report.pivot(index='Year', columns='Variety', values='Sim_Yield')

# 重新跑 CVaR 優化
opt_result = minimize(calculate_cvar, [0.33, 0.33, 0.34], args=(pivot_yield.values,),
                      bounds=[(0, 1), (0, 1), (0, 1)],
                      constraints=({'type': 'eq', 'fun': lambda w: np.sum(w) - 1}))

weights = opt_result.x

# 3. 計算「傳統決策」vs「優化決策」的表現
# 假設傳統決策是 100% 種植產量潛力最高的晚熟種 (Tardif)
traditional_yield = pivot_yield['Tardif']
# 優化後的農場總產量 (根據算出權重混合)
optimized_yield = np.dot(pivot_yield.values, weights)

# 4. 繪製最終對比圖 (這就是你的 Hero Image)
plt.figure(figsize=(12, 7))
sns.kdeplot(traditional_yield, label='Traditional (100% Tardif)', color='red', fill=True, alpha=0.3)
sns.kdeplot(optimized_yield, label='Optimized Portfolio (Our Model)', color='green', fill=True, alpha=0.5)

plt.axvline(x=7, color='black', linestyle='--', label='Bankruptcy Line (7 t/ha)')
plt.title('How Our Model Protects the Farm from Extreme Risks', fontsize=15)
plt.xlabel('Farm-level Total Yield (t/ha)', fontsize=12)
plt.ylabel('Risk Probability Density', fontsize=12)
plt.legend()
plt.grid(axis='y', alpha=0.3)

print("\n--- 最終優化建議 ---")
for i, var in enumerate(pivot_yield.columns):
    print(f"{var}: {weights[i]*100:.1f}%")

plt.show()

import pandas as pd
import numpy as np
from scipy.optimize import minimize
import matplotlib.pyplot as plt
import seaborn as sns

# 1. 定義擴展的策略參數
sowing_dates = ["04-01", "04-15", "05-01"]
varieties_config = {
    'Precoce': {'flowering': 900, 'pot': 10.5, 'heat_sens': 0.02},
    'Demi-tardif': {'flowering': 950, 'pot': 12.0, 'heat_sens': 0.035},
    'Tardif': {'flowering': 1050, 'pot': 14.5, 'heat_sens': 0.07}
}

def run_enhanced_simulation(weather_df):
    enhanced_results = []
    for year in range(weather_df.index.year.min(), weather_df.index.year.max() + 1):
        year_data = weather_df[weather_df.index.year == year]
        for s_date_str in sowing_dates:
            planting_date = pd.Timestamp(f"{year}-{s_date_str}")
            growing_season = year_data[year_data.index >= planting_date]
            for var_name, cfg in varieties_config.items():
                cumulative_gdd, flowering_date = 0, None
                for date, day_row in growing_season.iterrows():
                    cumulative_gdd += day_row['GDD']
                    if cumulative_gdd >= cfg['flowering']:
                        flowering_date = date
                        break
                if flowering_date:
                    w_start, w_end = flowering_date - pd.Timedelta(days=10), flowering_date + pd.Timedelta(days=10)
                    window = year_data[(year_data.index >= w_start) & (year_data.index <= w_end)]
                    heat_days = (window['Tmax'] > 35).sum()
                    water_def = window['Rain'].sum() - (len(window) * 5)
                    # 脆弱性回歸模擬
                    y_sim = cfg['pot'] * (1 - (heat_days * cfg['heat_sens']) - (abs(water_def)/10 * 0.01))
                    enhanced_results.append({'Year': year, 'Strategy': f"{var_name}_{s_date_str}", 'Yield': max(0, y_sim)})
    return pd.DataFrame(enhanced_results)

# 2. 數據轉換與優化
full_results = run_enhanced_simulation(weather_df)
yield_matrix = full_results.pivot(index='Year', columns='Strategy', values='Yield')

def min_cvar_optimize(matrix, alpha=0.05):
    n_strat = matrix.shape[1]
    init_w = np.array([1.0 / n_strat] * n_strat)
    def target(w):
        port_yield = np.dot(matrix.values, w)
        threshold = np.percentile(port_yield, alpha * 100)
        return -port_yield[port_yield <= threshold].mean()
    cons = ({'type': 'eq', 'fun': lambda w: np.sum(w) - 1}) # 修正後的完整行
    res = minimize(target, init_w, bounds=[(0, 1)]*n_strat, constraints=cons)
    return res.x

# 3. 輸出建議
opt_weights = min_cvar_optimize(yield_matrix)
print("\n--- Stratégie d'Exploitation Optimisée (MVP 2.0) ---")
for i, strategy in enumerate(yield_matrix.columns):
    if opt_weights[i] > 0.01:
        print(f"Stratégie {strategy}: {opt_weights[i]*100:.1f}% de la surface")

# 4. 繪製最終決策對比圖
plt.figure(figsize=(10, 6))
sns.kdeplot(np.dot(yield_matrix.values, opt_weights), label='Optimisé (Multi-semis/variétés)', color='green', fill=True)
sns.kdeplot(yield_matrix['Tardif_04-15'], label='Traditionnel (Tardif 100% - 15/04)', color='red', fill=True, alpha=0.3)
plt.axvline(x=7, color='black', linestyle='--', label='Seuil de Rentabilité')
plt.title('Réduction du Risque Extrême via la Diversité Phénologique')
plt.legend()
plt.show()

def get_kc(cumulative_gdd, variety_type):
    """根據積溫動態返回作物係數 Kc"""
    # 簡化版玉米 Kc 曲線
    if cumulative_gdd < 300: return 0.3  # 初期
    elif cumulative_gdd < 800: return 0.3 + (cumulative_gdd - 300) * (1.2 - 0.3) / 500  # 快速生長期
    elif cumulative_gdd < 1100: return 1.2  # 開花窗口 (最耗水)
    else: return 1.2 - (cumulative_gdd - 1100) * (0.5) / 500  # 成熟期
    return 0.5

def run_physio_simulation(weather_df, ru_max=100):
    results = []
    # 假設初始土壤水分為 80% RU
    current_sw = ru_max * 0.8

    # 這裡以單一年份/策略為例進行精細模擬
    # 實際上你會將此邏輯嵌入昨天的迴圈中
    for date, row in weather_df.iterrows():
        # 1. 計算潛在蒸散 ET0 (基於氣溫的簡化估算)
        et0 = 0.0023 * ((row['Tmax'] + row['Tmin'])/2 + 17.8) * (row['Tmax'] - row['Tmin'])**0.5 * 15
        et0 = max(2, min(et0, 8))

        # 2. 獲取當前 Kc 並計算實際需水 ETc
        # 假設我們已經在主迴圈中追蹤了 cumulative_gdd
        kc = get_kc(row['cumulative_gdd'], 'Tardif')
        etc = et0 * kc

        # 3. 計算水分壓力 Ks
        ks = min(1.0, current_sw / (0.4 * ru_max)) if current_sw < (0.4 * ru_max) else 1.0

        # 4. 更新土壤水分 (加上降雨，扣除實際蒸散)
        # 考慮到 Ks 會限制蒸散
        actual_et = etc * ks
        current_sw = max(0, min(ru_max, current_sw + row['Rain'] - actual_et))

        results.append({
            'Date': date,
            'Kc': kc,
            'Ks': ks,
            'Soil_Water': current_sw,
            'Daily_Yield_Loss': (1 - ks) * 0.05 # 每日水分壓力導致的潛在減產
        })
    return pd.DataFrame(results)

import pandas as pd
import numpy as np
import requests
from scipy.optimize import minimize
import matplotlib.pyplot as plt
import seaborn as sns

# --- 1. 重新抓取數據 (數據加油站) ---
def fetch_nasa_data():
    print("正在從 NASA 重新抓取 30 年氣候數據...")
    url = "https://power.larc.nasa.gov/api/temporal/daily/point?parameters=T2M_MAX,T2M_MIN,PRECTOTCORR&community=AG&longitude=-0.37&latitude=46.58&start=19950101&end=20241231&format=JSON"
    r = requests.get(url).json()
    df = pd.DataFrame(r['properties']['parameter'])
    df.index = pd.to_datetime(df.index)
    df.columns = ['Tmax', 'Tmin', 'Rain']
    # 計算基礎積溫 GDD
    df['GDD'] = ((df['Tmax'].clip(upper=30) + df['Tmin'].clip(lower=6)) / 2 - 6).clip(lower=0)
    return df

# --- 2. 生理模擬引擎 (FAO-56 邏輯) ---
def run_enhanced_simulation(weather_df):
    sowing_dates = ["04-01", "04-15", "05-01"]
    varieties_config = {
        'Precoce': {'flowering': 900, 'pot': 10.5, 'heat_sens': 0.02},
        'Demi-tardif': {'flowering': 950, 'pot': 12.0, 'heat_sens': 0.035},
        'Tardif': {'flowering': 1050, 'pot': 14.5, 'heat_sens': 0.07}
    }
    results = []
    for year in range(weather_df.index.year.min(), weather_df.index.year.max() + 1):
        year_data = weather_df[weather_df.index.year == year]
        for s_date_str in sowing_dates:
            p_date = pd.Timestamp(f"{year}-{s_date_str}")
            season = year_data[year_data.index >= p_date]
            for var, cfg in varieties_config.items():
                cum_gdd, flow_date = 0, None
                for d, row in season.iterrows():
                    cum_gdd += row['GDD']
                    if cum_gdd >= cfg['flowering']:
                        flow_date = d
                        break
                if flow_date:
                    win = year_data[(year_data.index >= flow_date - pd.Timedelta(days=10)) &
                                    (year_data.index <= flow_date + pd.Timedelta(days=10))]
                    heat_days = (win['Tmax'] > 35).sum()
                    water_def = (win['Rain'].sum() - len(win)*5)
                    y_sim = cfg['pot'] * (1 - (heat_days * cfg['heat_sens']) - (abs(water_def)/10 * 0.01))
                    results.append({'Year': year, 'Strategy': f"{var}_{s_date_str}", 'Yield': max(0, y_sim)})
    return pd.DataFrame(results)

# --- 3. 執行與壓力測試 ---
try:
    weather_df = fetch_nasa_data()

    # 執行 A: 當前氣候優化
    res_now = run_enhanced_simulation(weather_df)
    mat_now = res_now.pivot(index='Year', columns='Strategy', values='Yield')

    # 執行 B: 未來氣候 (+2°C) 模擬
    df_future = weather_df.copy()
    df_future['Tmax'] += 2.0
    df_future['Tmin'] += 2.0
    df_future['Rain'] *= 0.9 # 降雨減少 10%
    res_future = run_enhanced_simulation(df_future)
    mat_future = res_future.pivot(index='Year', columns='Strategy', values='Yield')

    print("\n✅ 全系統加載成功！正在生成壓力測試報告...")

    # 計算當前與未來的平均產量對比
    print(f"當前策略平均產量: {mat_now.mean().mean():.2f} t/ha")
    print(f"未來 (+2°C) 策略平均產量: {mat_future.mean().mean():.2f} t/ha")

except Exception as e:
    print(f"❌ 發生錯誤: {e}")

import pandas as pd
import numpy as np
import requests
from scipy.optimize import minimize
import matplotlib.pyplot as plt
import seaborn as sns

# --- 1. 數據抓取 ---
def fetch_nasa_data():
    url = "https://power.larc.nasa.gov/api/temporal/daily/point?parameters=T2M_MAX,T2M_MIN,PRECTOTCORR&community=AG&longitude=-0.37&latitude=46.58&start=19950101&end=20241231&format=JSON"
    r = requests.get(url).json()
    df = pd.DataFrame(r['properties']['parameter'])
    df.index = pd.to_datetime(df.index)
    df.columns = ['Tmax', 'Tmin', 'Rain']
    df['GDD'] = ((df['Tmax'].clip(upper=30) + df['Tmin'].clip(lower=6)) / 2 - 6).clip(lower=0)
    return df

# --- 2. 生理模擬引擎 ---
def run_enhanced_simulation(weather_df):
    sowing_dates = ["04-01", "04-15", "05-01"]
    varieties_config = {
        'Precoce': {'flowering': 900, 'pot': 10.5, 'heat_sens': 0.02},
        'Demi-tardif': {'flowering': 950, 'pot': 12.0, 'heat_sens': 0.035},
        'Tardif': {'flowering': 1050, 'pot': 14.5, 'heat_sens': 0.07}
    }
    results = []
    for year in range(weather_df.index.year.min(), weather_df.index.year.max() + 1):
        year_data = weather_df[weather_df.index.year == year]
        for s_date_str in sowing_dates:
            p_date = pd.Timestamp(f"{year}-{s_date_str}")
            season = year_data[year_data.index >= p_date]
            for var, cfg in varieties_config.items():
                cum_gdd, flow_date = 0, None
                for d, row in season.iterrows():
                    cum_gdd += row['GDD']
                    if cum_gdd >= cfg['flowering']:
                        flow_date = d
                        break
                if flow_date:
                    win = year_data[(year_data.index >= flow_date - pd.Timedelta(days=10)) &
                                    (year_data.index <= flow_date + pd.Timedelta(days=10))]
                    heat_days = (win['Tmax'] > 35).sum()
                    water_def = (win['Rain'].sum() - len(win)*5)
                    y_sim = cfg['pot'] * (1 - (heat_days * cfg['heat_sens']) - (abs(water_def)/10 * 0.01))
                    results.append({'Year': year, 'Strategy': f"{var}_{s_date_str}", 'Yield': max(0, y_sim)})
    return pd.DataFrame(results)

# --- 3. CVaR 優化器 (核心算法) ---
def min_cvar_optimize(matrix, alpha=0.05):
    n_strat = matrix.shape[1]
    init_w = np.array([1.0 / n_strat] * n_strat)
    def target(w):
        port_yield = np.dot(matrix.values, w)
        threshold = np.percentile(port_yield, alpha * 100)
        # 最小化最差 5% 情境下的預期損失
        return -port_yield[port_yield <= threshold].mean()
    cons = ({'type': 'eq', 'fun': lambda w: np.sum(w) - 1})
    res = minimize(target, init_w, bounds=[(0, 1)]*n_strat, constraints=cons)
    return res.x

# --- 4. 主執行程序與繪圖 ---
print("🚀 啟動全系統模擬與壓力測試...")
weather_df = fetch_nasa_data()

# 當前情境
mat_now = run_enhanced_simulation(weather_df).pivot(index='Year', columns='Strategy', values='Yield')
weights_now = min_cvar_optimize(mat_now)
portfolio_now = np.dot(mat_now.values, weights_now)

# 未來情境 (+2.5°C 更極端一點，讓效果更明顯)
df_future = weather_df.copy()
df_future['Tmax'] += 2.5
df_future['Tmin'] += 2.5
df_future['Rain'] *= 0.85 # 降雨減少 15%
mat_future = run_enhanced_simulation(df_future).pivot(index='Year', columns='Strategy', values='Yield')
weights_future = min_cvar_optimize(mat_future)
portfolio_future = np.dot(mat_future.values, weights_future)

# 繪製對比圖
plt.figure(figsize=(12, 6))
sns.kdeplot(portfolio_now, label='Climat Actuel (Optimisé)', color='green', fill=True, alpha=0.3)
sns.kdeplot(portfolio_future, label='Scénario +2.5°C (Optimisé)', color='red', fill=True, alpha=0.3)
plt.axvline(x=7, color='black', linestyle='--', label='Seuil de Rentabilité (7 t/ha)')

plt.title('Analyse de la Résilience : Aujourd\'hui vs Futur Échauffé', fontsize=14)
plt.xlabel('Rendement du Domaine (t/ha)')
plt.ylabel('Densité de Probabilité')
plt.legend()

# 顯示關鍵風險指標
cvar_now = np.percentile(portfolio_now, 5)
cvar_future = np.percentile(portfolio_future, 5)
print(f"\n📊 風險報告：")
print(f"- 當前最差 5% 年份平均產量 (CVaR): {cvar_now:.2f} t/ha")
print(f"- 未來最差 5% 年份平均產量 (CVaR): {cvar_future:.2f} t/ha")
print(f"- 極端風險缺口 (Risk Gap): {cvar_now - cvar_future:.2f} t/ha")

plt.show()